name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
  - title: "🗂 Datasets"
    labels:
      - "dataset"
  - title: "🔬 Experiments"
    labels:
      - "experiment"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧹 Maintenance"
    labels:
      - "maintenance"
      - "dependencies"
      - "refactoring"
      - "cosmetic"
      - "chore"

autolabeler:
  - label: "feature"
    branch:
      - "/features{0,1}\/.+/"
  - label: "dataset"
    branch:
      - "/datasets{0,1}\/.+/"
  - label: "experiment"
    branch:
      - "/experiments{0,1}\/.+/"
  - label: "bug"
    branch:
      - "/fix\/.+/"
      - "/bugfix\/.+/"
      - "/bug\/.+/"
  - label: "maintenance"
    branch:
      - "/maintenance\/.+/"
      - "/refactoring\/.+/"
      - "/cosmetics{0,1}\/.+/"
      - "/chores{0,1}\/.+/"
  - label: dependencies
    branch:
      - "/dependencies\/.+/"
  - label: "documentation"
    branch:
      - "/docs{0,1}\/.+/"
      - "/documentation\/.+/"

change-template: "- $TITLE (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions

version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch

template: |
  ## Changes

  $CHANGES
