# path to root directory
# this requires PROJECT_ROOT environment variable to exist
# PROJECT_ROOT is inferred and set by rootutils package in entrypoint scripts
root_dir: ${oc.env:PROJECT_ROOT}

# path to the cache directory
cache_dir: ${paths.root_dir}/.cache

# path to data directory
data_dir: ${paths.root_dir}/data

# path to logging directory
log_dir: ${paths.root_dir}/logs

# path to model directory
model_dir: ${paths.root_dir}/models

# path to output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during the run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to working directory
work_dir: ${hydra:runtime.cwd}
